# Generated by Django 4.2.4 on 2023-08-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0002_alter_passenger_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='address',
        ),
    ]
